os: osx
osx_image: xcode12.0
language: swift
script: 
  - xcodebuild build-for-testing -project RickAndJamesTest.xcodeproj -scheme RickAndJamesTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  - xctool run-tests -project RickAndJamesTest.xcodeproj -scheme RickAndJamesTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
