os: osx
osx_image: xcode12.0
language: swift
script: 
  # - xcodebuild build-for-testing -project RickAndJamesTest.xcodeproj -scheme RickAndJamesTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  # - xctool run-tests -project RickAndJamesTest.xcodeproj -scheme RickAndJamesTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -project RickAndJamesTest.xcodeproj -scheme RickAndJamesTest -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.0
