## DOCUMENTATION
## - https://medium.com/@MaverickHitesh/setting-up-travis-ci-for-ios-project-b3cb7963b420   
## - https://medium.com/@canyouimaginei/travis-ci-for-ios-6c0382a371f5
## - https://docs.travis-ci.com/user/caching/

os: osx
osx_image: xcode12
language: swift
script:
  - xcodebuild test -project RickAndJamesTest.xcodeproj -scheme RickAndJamesTest -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.0'
